### ISSUE TITLE
styling should look stylish

### ISSUE THREAD

**Issue by gregdyke** [CodeYourFuture/fundamentals-blockly#15]
Do this on existing html, as work for reactifying will not be in the mvp

**Comment by SallyMcGrath** [comment]
<img width="1500" alt="Screenshot 2022-03-08 at 20 21 50" src="https://user-images.githubusercontent.com/42203406/157437263-05dd31ce-a786-4527-a4dc-a7d7fe1eb86a.png">
<img width="1510" alt="Screenshot 2022-03-07 at 21 41 59" src="https://user-images.githubusercontent.com/42203406/157437273-4e471b00-6454-41c2-9f70-f09723c899af.png">

**Comment by SallyMcGrath** [comment]
<img width="1512" alt="Screenshot 2022-03-07 at 21 15 27" src="https://user-images.githubusercontent.com/42203406/157437358-dafad519-ae11-4e57-8f6d-b4eeb3f71720.png">
