### ISSUE TITLE
recap html/css knowledge

### ISSUE THREAD

**Issue by gregdyke** [CodeYourFuture/fundamentals-blockly#21]
html and basic css is expected from ITD course, but should be recapped

Add in a link to the crash course -> put it as prep before week 1 + in blockly footer

**Comment by SallyMcGrath** [comment]
https://github.com/CodeYourFuture/fundamentals-blockly/tree/feature/recap-in-footer
https://github.com/CodeYourFuture/syllabus/commit/83b65fc9d17bfd9bfdbea5a681c25797f6ae0f6b
