### ISSUE TITLE
Mention Devtools

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/fundamentals-blockly#60]
Given a user playing with https://blocks.codeyourfuture.io/#exercise_set_colours
When I set the attribute "id" to "23"
Then the HTML changes
And I do not see the change
And I don't know what's gone on

=> Can we guide the user to Inspect the HTML with Devtools?
<img width="1508" alt="Screenshot 2022-03-30 at 20 00 58" src="https://user-images.githubusercontent.com/42203406/160912533-dc084d2c-09b9-4645-aac4-8108a42f5d32.png">

**Comment by Dedekind561** [comment]
Addressed in this PR https://github.com/CodeYourFuture/fundamentals-blockly/pull/92
