### ISSUE TITLE
Explicitly get number/text from input box

### ISSUE THREAD

**Issue by gregdyke** [CodeYourFuture/fundamentals-blockly#90]
Currently the "get the value of <input> with id ..." block tries to convert the input to a number if possible (so that the input can be used as part of arithmetic operations, e.g. put into an array then sum the array).

- this creates superfluous/potentially confusing getNumberOrString calls in the generated code
- empty string gets transformed to zero

Proposed solution:
- Add a dropdown to the block that switches between "get the text value" and "get numeric value" with default to text
- Change the generated code to only use/call getNumberOrString if needed (maybe change it to convertToNumber with a default of 0?)
- Change the instructions to mention selecting "numeric" in the dropdown, where relevant

**Comment by gregdyke** [comment]
To add the dropdown, add an entry to the args0 array of `get_input_value_with_id` in blockly-dom.js and modify the message0 (%1 %2 etc are placeholders using 1-indexing into args0). See `set_attribute` for a block with a dropdown. (blocks can be defined with json or through a javascript API - these particular blocks are defined in json)

For the generated code, see

  - `Blockly.JavaScript["get_input_value_with_id"]` current generated code (note that provideFunction_ ensures that the given function is only output once, even if there are multiple blocks. Also "ORDER_MEMBER" is not the correct priority for the current code, but it's close enough that it does not need fixing in this ticket - ORDER_MEMBER *is* the correct priority for the code that just returns `.value` without wrapping it in the function)
  - `Blockly.JavaScript["set_attribute"]` shows how to get the value provided in the dropdown

**Comment by gregdyke** [comment]
I just realised this will break people's existing solutions where there a numeric value is needed. We could invest the extra effort to create a non breaking change for them (there would be 3 modes: text, numeric, best guess and we would add a mutator on loading that selects best guess as the default). Or we could just accept that it will break a few people's code, which is not the end of the world

**Comment by Dedekind561** [comment]
Hi @gregdyke , I've raised a PR for this issue #91 but there are a few things I don't understand in your comments:

> note that provideFunction_ ensures that the given function is only output once,

Not sure exactly what this means. Does it mean if 2 connected blocks separately reference a function, say `convertToNumber`, then it will only appear once in the generated code?

> Also "ORDER_MEMBER" is not the correct priority for the current code, but it's close enough that it does not need fixing in this ticket - ORDER_MEMBER is the correct priority for the code that just returns .value without wrapping it in the function)

I'm not sure what ORDER_MEMBER is doing. I've included it as the first element in the returned array inside the source for `get_input_value_with_id` and it seems to work :grin: 

Also, I did a cursory search online for the Blockly API but couldn't see docs for `provideFunction_` - please could you point me in the right direction so I can check out exactly what these things are doing.

**Comment by gregdyke** [comment]
> Not sure exactly what this means. Does it mean if 2 connected blocks separately reference a function, say convertToNumber, then it will only appear once in the generated code?

That's right, yes

ORDER_MEMBER is saying that the loosest binding "operator" in the returned expression is the . (which is one of the most tightly binding operators, so it means that the generated code will almost never need surrounding with additional brackets) https://developers.google.com/blockly/guides/create-custom-blocks/operator-precedence

(if you were returning an addition, you would say ORDER_ADDITION, and if the block that asked for your returned expression was subsequently doing multiplication, blockly would know to add parentheses appropriately)

https://developers.google.com/blockly/reference/js/blockly.generator_class.providefunction__1_method.md (I'm not sure what "protected" means in this context)

**Comment by Dedekind561** [comment]
Fixed with #91
